version: '3.8'

services:
  backend:
    image: technograd/flask-backend:latest
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    networks:
      - app-network
    restart: unless-stopped
    container_name: flask-backend

  frontend:
    image: technograd/express-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - BACKEND_URL=http://flask-backend:5001
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped
    container_name: express-frontend

networks:
  app-network:
    driver: bridge