apiVersion: v1
kind: Service
metadata:
  name: express-frontend-service
spec:
  selector:
    app: express-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
